#!/bin/bash

REMOTE=gcr.io/test-cg

cd `dirname $0`
TIMESTAMP=`date --utc +%Y%m%d%H%M%S`
TAG=letsencryptor:${1-$TIMESTAMP}
echo Building docker image with tag $TAG
docker build -t $TAG .
echo Built docker image with tag $TAG
echo Tagging for remote repo as $REMOTE/$TAG
docker tag $TAG $REMOTE/$TAG
